area_name: "Providencia"
bbox: [-33.462, -70.643, -33.404, -70.571]  # [south, west, north, east]
highway_regex: "^(motorway|trunk|primary|secondary|tertiary|unclassified|residential|living_street|service|pedestrian|track|path|footway|cycleway)$"
timeout_s: 120
overpass_urls:
  - "https://overpass-api.de/api/interpreter"
  - "https://z.overpass-api.de/api/interpreter"
  - "https://overpass.kumi.systems/api/interpreter"
user_agent: "fase2-providencia-etl/infra/1.2"
