bbox: [-33.4450, -70.6315, -33.4180, -70.5710]   # [S, W, N, E]
overpass_url: "https://overpass-api.de/api/interpreter"
timeout_s: 180
# Altura por defecto si no hay tags (m)
default_level_h: 3.2
default_levels: 5
